GET http://127.0.0.1:3000/api/diakok HTTP/1.1

###
GET http://127.0.0.1:3000/api/jegyek/6 HTTP/1.1

###


POST http://127.0.0.1:3000/api/insertinto HTTP/1.1
content-type: application/json

{
    "nev": "Pizsgsdfsfza",
    "ar": 7002,
    "finom": "Nagydgoon fino"
}